### ISSUE TITLE
Feature Request: Custom Wallpaper

### ISSUE THREAD

**Issue by Antitype** [gavinhungry/Xposed-NoLockscreenWallpaper#1]
Like to have a feature to add a wallpaper of choice with Google Photos or any other application.

**Comment by gavinhungry** [comment]
I don't know about "any other application," but I think you're looking for [Xposed Lockscreen Wallpaper](http://repo.xposed.info/module/jh.xposed.lockscreenwallpaper).

**Comment by Antitype** [comment]
Doesn't support Marshmallow. Don't want to use GravityBox either.

**Comment by gavinhungry** [comment]
Well, sorry. Custom wallpaper support on the module titled "No Lockscreen Wallpaper" seems kind of silly.

**Comment by Antitype** [comment]
Could I request you to make one if you have spare time?
